token: ""
discordServerIds: 
  - 0
# Still in it's early phases...
# prune-time: 
#   days: 1
#   seconds: 0
#   microseconds: 0
#   milliseconds: 0
#   minutes: 0
#   hours: 0
#   weeks: 0

# creation-date-limit:
#   days: 0
#   seconds: 0
#   microseconds: 0
#   milliseconds: 0
#   minutes: 0
#   hours: 0
#   weeks: 26
  
